### ISSUE TITLE
it would be nice if you could provide an array of redux actions and take multiple snapshots from that

### ISSUE THREAD

**Issue by faceyspacey** [instea/react-native-snap-shooter#1]
So, this is absolutely amazing. But it seems it's only for rendering one state of your app. It would be awesome if you could provide an array of redux actions and it would dispatch each and then take a snapshot. What do you think?

**Comment by sodik82** [comment]
hello.
I have in my plans to provide a possibility to take multiple snapshots of the application (in different states). However for the start I would not like to "limit" usage to the redux setups only. Rather I would maybe more generic in the sense that the responsibility to manage application state would be in hands of the `demo` application and the framework would just provide ability to trigger snapshots.

Is such approach fine with you? I try to spend a little time on it soon :)

**Comment by sodik82** [comment]
with version `0.5` it is now possible to take multiple snapshots.

**Comment by faceyspacey** [comment]
awesome!
